import React, { useState } from 'react';
import { ChevronDown, X } from 'lucide-react';
import { StatusChip } from '../common/ui';
import { t } from '../i18n/ui';
import { screens, type SectionId } from './navigation';

function BrandMark() {
  return <div className="flex items-center"><img src="/branding/textifai-logo-full.png" alt="TextifAI" className="h-8 w-auto" /></div>;
}

function SettingsModal({ onClose }: { onClose: () => void }) {
  return <div className="fixed inset-0 z-40 flex items-center justify-center bg-[#3a2a21]/35 p-4"><div className="w-full max-w-2xl rounded-txf-card border border-txf-border-strong bg-txf-surface shadow-txf-floating"><div className="flex items-center justify-between border-b border-txf-border bg-txf-surface-muted p-5"><div><h2 className="text-lg font-semibold">{t('shell.settings')}</h2><p className="text-sm text-txf-subtle">{t('shell.settings_note')}</p></div><button type="button" onClick={onClose} className="rounded-full p-2 hover:bg-txf-surface-soft"><X size={18} /></button></div></div></div>;
}

function SidebarNav({ active, setActive }: { active: SectionId; setActive: (id: SectionId) => void }) {
  return <><nav className="space-y-1 bg-txf-sidebar">{screens.map((screen) => { const Icon = screen.icon; const selected = active === screen.id; return <button key={screen.id} onClick={() => setActive(screen.id)} className={`flex w-full items-center gap-3 rounded-2xl px-3 py-2.5 text-left text-sm transition ${selected ? 'bg-txf-nav-active text-txf-nav-active-text shadow-sm' : 'text-txf-muted hover:bg-txf-surface-soft hover:text-txf-text'}`}><Icon size={17} /><span>{t(screen.label)}</span></button>; })}</nav><div className="mt-5 rounded-txf-card border border-txf-border bg-txf-surface p-4 text-xs text-txf-subtle"><b className="text-txf-text">{t('shell.localFirst.title')}</b><br />{t('shell.localFirst.body')}</div></>;
}

export function AppShell({ active, setActive, openProjectLabel, children }: { active: SectionId; setActive: (id: SectionId) => void; openProjectLabel?: string; children: React.ReactNode }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  return <div className="min-h-screen h-screen txf-surface-shell text-txf-text p-2 md:p-4 overflow-hidden"><div className="mx-auto h-full w-full max-w-none overflow-hidden rounded-txf-card border border-txf-border-strong bg-txf-frame shadow-txf-panel"><header className="bg-txf-frame flex items-center justify-between border-b border-txf-border-strong px-5 py-4"><button type="button" onClick={() => setActive('overview')} className="text-left"><BrandMark /><div className="text-xs text-txf-subtle">{t('shell.tagline')}</div></button><div className="flex flex-wrap items-center justify-end gap-2 text-xs">{openProjectLabel ? <StatusChip>{t('shell.active_project')}: {openProjectLabel}</StatusChip> : <StatusChip>{t('shell.no_active_project')}</StatusChip>}<StatusChip>{t('shell.vaerlReady')}</StatusChip></div></header><div className="grid h-[calc(100%-73px)] min-h-0 grid-cols-12"><aside className="col-span-12 flex min-h-0 flex-col border-r border-txf-border-strong bg-txf-sidebar p-3 md:col-span-2"><SidebarNav active={active} setActive={setActive} />{openProjectLabel ? <div className="mt-4 rounded-2xl border border-txf-border bg-txf-surface p-4 text-xs text-txf-subtle"><div className="uppercase tracking-[0.18em]">{t('shell.active_project')}</div><div className="mt-2 text-sm font-semibold text-txf-text">{openProjectLabel}</div></div> : null}<div className="relative mb-6 mt-auto pt-4">{menuOpen ? <div className="absolute bottom-16 left-0 right-0 z-20 rounded-2xl border border-txf-border-strong bg-txf-surface p-2 text-sm shadow-txf-floating"><button type="button" onClick={() => { setSettingsOpen(true); setMenuOpen(false); }} className="w-full rounded-xl px-3 py-2 text-left hover:bg-txf-surface-soft">{t('shell.settings')}</button><button type="button" onClick={() => setActive('hub')} className="w-full rounded-xl px-3 py-2 text-left hover:bg-txf-surface-soft">{t('shell.menu.project_workspace')}</button><button type="button" className="w-full rounded-xl px-3 py-2 text-left text-txf-subtle" disabled>{t('shell.menu.dev_tools_pending')}</button></div> : null}<button type="button" onClick={() => setMenuOpen((v) => !v)} className="w-full rounded-2xl border border-txf-border bg-txf-surface p-3 text-left hover:border-txf-border-strong hover:bg-txf-surface-soft"><div className="flex items-center gap-2.5"><div className="shrink-0 flex h-9 w-9 items-center justify-center rounded-full bg-txf-action text-txf-nav-active-text font-semibold">A</div><div className="min-w-0 flex-1 leading-tight"><div className="truncate text-sm font-semibold">{t('shell.user.localAuthor')}</div><div className="truncate whitespace-nowrap text-xs text-txf-subtle">{t('shell.user.privateWorkspace')}</div></div><ChevronDown size={16} className="shrink-0" /></div></button></div></aside><main className="col-span-12 min-h-0 overflow-y-auto bg-txf-canvas md:col-span-10">{children}</main></div></div>{settingsOpen ? <SettingsModal onClose={() => setSettingsOpen(false)} /> : null}</div>;
}
