import React from 'react';
import { AlertTriangle, CheckCircle2, Search } from 'lucide-react';
import { Button, TopBar } from '../../common/ui';
import { t } from '../../i18n/ui';

export type ProjectHubNotice = {
  id: string;
  tone: 'info' | 'warning' | 'danger';
  message: string;
};

export function ProjectHubView({ projectRows, projectHubNotice, chaptersProcessed, artifactsCount, warningsVisible, openProjectTitle, selectedProjectStatus, selectedProjectTitle, onNewIngestion }: { projectRows: React.ReactNode; projectHubNotice?: ProjectHubNotice | null; chaptersProcessed: number; artifactsCount: number; warningsVisible: number; openProjectTitle: string; selectedProjectStatus: string; selectedProjectTitle: string; onNewIngestion: () => void; }) {
  const noticeClass = projectHubNotice?.tone === 'danger' ? 'bg-[var(--txf-color-danger-soft)]' : projectHubNotice?.tone === 'warning' ? 'bg-[var(--txf-color-warning-soft)]' : 'bg-txf-surface-muted';
  return <section className="bg-txf-canvas"><TopBar title={t('nav.hub')} subtitle={t('project.subtitle')} actions={<Button onClick={onNewIngestion}>{t('project.new_ingestion')}</Button>} /><div className="grid grid-cols-12 gap-5 bg-txf-canvas p-5"><div className="col-span-12 space-y-4 bg-txf-canvas lg:col-span-8">{openProjectTitle ? <div className="rounded-3xl border border-txf-border bg-txf-surface p-4 text-sm"><span className="font-medium">{t('project.open_indicator')}</span> {openProjectTitle}</div> : null}<div className="rounded-3xl border border-txf-border bg-txf-surface p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-lg">{t('project.available_workspaces')}</h2><p className="text-sm text-txf-subtle">{t('project.api_note')}</p></div><Search size={18} className="text-txf-subtle" /></div><div className="mt-4 space-y-3 bg-txf-surface">{projectRows}</div>{projectHubNotice ? <div className={`mt-4 rounded-2xl border border-txf-border p-3 text-sm text-txf-text ${noticeClass}`}><AlertTriangle size={16} className="inline" /> {projectHubNotice.message}</div> : null}</div></div><aside className="col-span-12 space-y-4 bg-txf-canvas lg:col-span-4"><div className="rounded-3xl border border-txf-border bg-txf-surface p-5"><h3 className="font-semibold">Resumen del proyecto</h3><div className="mt-4 space-y-3 text-sm"><div><span className="font-medium">Proyecto seleccionado:</span> {selectedProjectTitle || t('project.none_selected')}</div><div><span className="font-medium">{t('project.summary_status')}</span> {selectedProjectStatus}</div><div className="flex items-center gap-2"><CheckCircle2 size={16} /> {t('project.indexed_chapters', { count: chaptersProcessed })}</div><div className="flex items-center gap-2"><CheckCircle2 size={16} /> {t('project.artifacts', { count: artifactsCount })}</div><div className="flex items-center gap-2"><AlertTriangle size={16} /> {t('project.visible_warnings', { count: warningsVisible })}</div></div><div className="sr-only">{t('project.contract')} {t('project.manifest_name')} {t('project.contract_note')} {t('project.future')} {t('project.future_manifest')} {t('project.packaged_workspace')}</div></div></aside></div></section>;
}
